### ISSUE TITLE
Week #14: Data Structures

### ISSUE THREAD

**Issue by tstamler** [gw-sd-2016/harddrivecache#3]
@cctoombs @twood02

Sorry for no issue after Thanksgiving, I wasn't sure if we needed to do one. In the last couple of weeks though, I have improved the functionality of the filesystem. It now automatically creates directories that may not exist on the SSD but may need to be added for files that are being added. It also deletes files from the SSD when they are deleted from the HD. 

Most importantly, I added a hash table to keep track of all the files on the SSD and keep statistics that might affect the caching algorithms such as last access time, number of accesses, last update time, number of updates, and file size. I think all of these might be useful for deciding what files should be kept on the SSD.

**Comment by twood02** [comment]
sounds good.  If you want to meet to discuss types of stats to keep and how to use them, send me a message.
